# Generated by Django 4.1.3 on 2024-01-10 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customerEmail', models.EmailField(max_length=254)),
                ('customerPhone', models.IntegerField(max_length=9)),
                ('date', models.DateField()),
                ('open', models.BooleanField()),
                ('orderName', models.CharField(max_length=12)),
                ('orderType', models.CharField(max_length=12)),
                ('uid', models.CharField(max_length=50)),
            ],
        ),
    ]
