# Generated by Django 4.1.3 on 2024-01-10 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hhpnwapi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='customerPhone',
            field=models.IntegerField(),
        ),
    ]
