# Generated by Django 4.1.3 on 2024-01-12 19:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hhpnwapi', '0005_alter_items_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderMenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('items', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hhpnwapi.items')),
                ('orders', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hhpnwapi.orders')),
            ],
        ),
    ]
