# Generated by Django 4.1.3 on 2024-01-16 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hhpnwapi', '0011_alter_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='uid',
            field=models.TextField(max_length=50),
        ),
    ]
