# Generated by Django 4.1.3 on 2024-01-16 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hhpnwapi', '0012_alter_orders_uid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='date',
            field=models.IntegerField(),
        ),
    ]
