# Generated by Django 4.1.3 on 2024-01-16 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hhpnwapi', '0016_alter_orders_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='date',
            field=models.IntegerField(),
        ),
    ]
