# Generated by Django 4.1.3 on 2024-01-17 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hhpnwapi', '0017_alter_orders_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='customerEmail',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
